server:
  port: 8080
  address: 127.0.0.1
  ssl:
    keyStore: classpath:client.p12
    keyStorePassword: 123456
    keyStoreType: PKCS12
    keyAlias: client
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
spring:
  application:
    name: springboot-gateway
  cloud:
    gateway:
#      default-filters:
#        - PrefixPath=/v1,/v2
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: eureka-client-v1
#          uri: lb://eureka-client
#          predicates:
#            - Path=/hello1/**
#          filters:
#            - PrefixPath=/v1
#        - id: eureka-client-v2
#          uri: lb://eureka-client
#          predicates:
#            - Path=/hello2/**
#          filters:
#            - PrefixPath=/v2
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:51001/eureka